server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-2ze8v9g2o013w44f8wo.mysql.rds.aliyuncs.com:3306/test_m?characterEncoding=utf-8&useSSL=false
    username: weiwan
    password: weiwan=123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.ht.hhr.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
logging:
  level:
    com.ht.hhr.mapper: trace
wechat:
  appId: wxe89ca7e0e8457f64
  secret: a237050f08dc5e26833fc619fb91cc92